name: scrollable_positioned_list_index
description: >
  A Flutter widget that provides a synchronized, navigable outline index for scrollable lists, 
  allowing easy section jumping and current position highlighting.
version: 0.1.0
homepage: https://github.com/vitorhugo1207/scrollable_positioned_list_index
repository: https://github.com/vitorhugo1207/scrollable_positioned_list_index

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics:
  - scroll
  - list
  - navigation
  - index
  - outline
